local AppName = ...
local AL = LibStub("AceLocale-3.0")
local L = AL:NewLocale(AppName, "enUS", true)

L["focus"] = "Focus"
L["mouseover"] = "Mouseover"
L["pet"] = "Pet"
L["playertarget"] = "Target"
L["arena%d"]="Arena%d"
L["|cffeda55fControl + Left Click|r to lock frames"] = "|cffeda55fControl + Left Click|r to lock frames"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55fDrag|r to move the frame"
L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55fLeft Click|r to lock/unlock frames"
L["|cffeda55fShift + Left Click|r to toggle sound"] = "|cffeda55fShift + Left Click|r to toggle sound"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55fRight Click|r to open the configuration window"

-----------------------------------------------------------------------------

L = AL:NewLocale(AppName, "zhCN")
if L then
L["|cffeda55fControl + Left Click|r to lock frames"] = "|cffeda55fCtrl+点击|r锁定所有框架"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55f拖拽|r 移动位置"
L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55f点击|r锁定/解锁框架"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55f右击|r打开设置窗口"
L["|cffeda55fShift + Left Click|r to toggle sound"] = "|cffeda55fShift + 左键点击|r 来开启/关闭音效"
L["focus"] = "焦点"
L["mouseover"] = "鼠标悬停"
L["pet"] = "宠物"
L["playertarget"] = "目标"

-- opt
L["Anchor to Mouse"] = "锚点定位到鼠标"
L["Auto hide"] = "自动隐藏"
L["Background Color"] = "背景颜色"
L["Background Options"] = "背景选项"
L["Background Texture"] = "背景材质"
L["Background Tile Size"] = "背景网格尺寸"
L["Border Color"] = "边框颜色"
L["Border Texture"] = "边框材质"
L["Border Thickness"] = "边框厚度"
L["Close range section"] = "近距离项"
L["Color"] = "颜色"
L["Copy section settings to other units"] = "复制分段设置到其他单位"
L["Default section"] = "默认项"
L["Enable this color section"] = "开启此色彩项目"
L["Enabled"] = "开启"
L["Enemy only"] = "仅敌对"
L["Enemy only sound"] = "敌对报警音"
L["Font"] = "字体"
L["Font outline"] = "字体描边"
L["Font size"] = "字号"
L["Frame strata"] = "框架显示层面"
L["Frame's background color"] = "框架背景颜色"
L["Frame's border color"] = "框架边框颜色"
L["Height"] = "高度"
L["Hide the background if the range display is not active"] = "如果距离显示没有被激活则隐藏背景"
L["High"] = "最高层"
L["Lock/Unlock display frame"] = "锁定或解锁显示框"
L["Locked"] = "锁定"
L["Long range section"] = "远距离项"
L["Low"] = "最低层"
L["Medium"] = "中间层"
L["Medium range section"] = "中距离项"
L["Mute"] = "静音"
L["None"] = "无"
L["Normal"] = "正常"
L["Out of range section"] = "超出距离项"
L["Over limit display"] = "超出距离显示"
L["Over limit text"] = "超过限制文字"
L["Play a sound when entering this range"] = "当进入这个距离范围时播放一个音效"
L["Range limit"] = "距离限制"
L["Ranges above this are not reported"] = "不提醒超出此数值的距离"
L["Reverse"] = "相反"
L["Short range section"] = "短距离项"
L["Show max-min instead of min-max"] = "显示最大-最小替换最小-最大"
L["Show range for enemy targets only"] = "仅显示敌对目标的距离"
L["Show/Hide display if the target is further than range limit"] = "在目标超出距离时显示/隐藏距离框体"
L["Strata"] = "层级"
L["Text"] = "文字"
L["Texture to use for the frame's background"] = "框架背景的材质"
L["Texture to use for the frame's border"] = "框架边框的材质"
L["The size used to tile the background texture"] = "网格背景尺寸"
L["The text to display for this section"] = "显示此项的文字"
L["The text to display when you are further than range limit"] = "显示当你超过距离限制的文字"
L["The thickness of the border"] = "设置边框厚度"
L["Thick"] = "加粗"
L["Tile Background"] = "网格背景"
L["Tile the background texture"] = "网格背景材质"
L["Toggle sound"] = "开启/关闭音效"
L["Use Section Colors"] = "使用分段颜色"
L["Use section colors for background and background color for text"] = "使用该颜色作为背景与背景文字的颜色"
L["Use warning sound for enemy targets only"] = "仅对敌对目标使用警告声"
L["Warning Sound"] = "报警音效"
L["Warning Sound Name"] = "报警音效名字"
L["Width"] = "宽度"

end

L = AL:NewLocale(AppName, "zhTW")
if L then
L["|cffeda55fControl + Left Click|r to lock frames"] = "|cffeda55fCtrl+左鍵|r 鎖定所有框架"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55f拖拽|r 移動位置"
L["|cffeda55fLeft Click|r to lock/unlock frames"] = "|cffeda55f左鍵|r 鎖定/解鎖框架"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55f右鍵|r 開啟設定視窗"
L["|cffeda55fShift + Left Click|r to toggle sound"] = "|cffeda55fShift + 左鍵|r 切換音效"
L["focus"] = "專注目標"
L["mouseover"] = "滑鼠目標"
L["pet"] = "寵物"
L["playertarget"] = "目標"

-- opt
L["Anchor to Mouse"] = "跟隨滑鼠移動"
L["Auto hide"] = "自動隱藏"
L["Background Color"] = "背景顏色"
L["Background Options"] = "背景選項"
L["Background Texture"] = "背景材質"
L["Background Tile Size"] = "背景網格大小"
L["Border Color"] = "邊框顏色"
L["Border Texture"] = "邊框材質"
L["Border Thickness"] = "邊框粗細"
L["Close range section"] = "近距離設定"
L["Color"] = "顏色"
L["Copy section settings to other units"] = "將這裡的設定複製到其他目標單位"
L["Default section"] = "預設設定"
L["Enable this color section"] = "啟用顏色設定"
L["Enabled"] = "啟用"
L["Enemy only"] = "只顯示敵方"
L["Enemy only sound"] = "只播放敵方音效"
L["Font"] = "字體"
L["Font outline"] = "字體外框"
L["Font size"] = "字體大小"
L["Frame strata"] = "框架層級"
L["Frame's background color"] = "框架背景顏色"
L["Frame's border color"] = "框架邊框顏色"
L["Height"] = "高度"
L["Hide the background if the range display is not active"] = "距離顯示停用時自動隱藏背景"
L["High"] = "高"
L["Lock/Unlock display frame"] = "鎖定/解鎖顯示框"
L["Locked"] = "鎖定"
L["Long range section"] = "長距離設定"
L["Low"] = "低"
L["Medium"] = "中"
L["Medium range section"] = "中距離設定"
L["Mute"] = "靜音"
L["None"] = "無"
L["Normal"] = "正常"
L["Out of range section"] = "超出距離設定"
L["Over limit display"] = "超出限制顯示"
L["Over limit text"] = "超過限制文字"
L["Play a sound when entering this range"] = "進入距離範圍內時播放音效"
L["Range limit"] = "距離限制"
L["Ranges above this are not reported"] = "不要提醒超出此數值的距離"
L["Reverse"] = "對調"
L["Short range section"] = "短距離設定"
L["Show max-min instead of min-max"] = "最大-最小 對調為 最小-最大"
L["Show range for enemy targets only"] = "只顯示敵對目標的距離"
L["Show/Hide display if the target is further than range limit"] = "目標超出距離限制時顯示/隱藏距離框架"
L["Strata"] = "層級"
L["Text"] = "文字"
L["Texture to use for the frame's background"] = "框架背景的材質"
L["Texture to use for the frame's border"] = "框架邊框的材質"
L["The size used to tile the background texture"] = "背景材質的網格大小"
L["The text to display for this section"] = [=[這個距離範圍所顯示的文字
(%d, %d 為 最小, 最大距離)]=]
L["The text to display when you are further than range limit"] = [=[超出距離限制範圍所顯示的文字
(%d 為最小距離值)]=]
L["The thickness of the border"] = "邊框粗細"
L["Thick"] = "粗"
L["Tile Background"] = "背景網格"
L["Tile the background texture"] = "背景材質網格"
L["Toggle sound"] = "切換音效"
L["Use Section Colors"] = "使用選擇的顏色"
L["Use section colors for background and background color for text"] = "背景和文字的背景色使用這裡所選擇的顏色"
L["Use warning sound for enemy targets only"] = "只有目標是敵對時才播放警告音效"
L["Warning Sound"] = "警告音效"
L["Warning Sound Name"] = "警告音效名稱"
L["Width"] = "寬度"
L["arena%d"]="競技場%d"
L["RangeDisplay: "] = "顯示距離: "
L["RangeDisplay"] = "距離"

end

