--save this file in UTF-8 for special chars

local L = LibStub("AceLocale-3.0"):NewLocale( "EmoteCenter", "zhTW" )

if not L then return end


-- <- Translate these strings ->
L["EmoteCenter"] = "表情"
	-- Random addon strings
L["Last Emote Used"] = "上次的表情"
L["Reset the options to default."] = "重置選項為預設。"
L["Toggle the display of slash commands."] = "切換指令的顯示。"
L["Show slash commands."] = "顯示指令。"
L["Toggle the display of A&V flags."] = "切換動&音標籤的顯示。"
L["Show A&V flags."] = "顯示動&音標籤。"
L["Currently:"] = "目前："
L["Toggle the display of the minimap button."] = "切換小地圖按鈕的顯示"
L["Show minimap button."] = "顯示小地圖按鈕。"
L["Shown"] = "顯示"
L["Hidden"] = "隱藏"

-- Favorites
L["Favorites"] = "最愛"
L["Shift-Click on an emote to add to or remove from favorites."] = "Shift點擊一個表情加入最愛或從最愛中移除。"
L[" removed from favorites."] = "從最愛移除。"
L[" added to favorites."] = "加入最愛。"


-- Emote Data Types
L["Friendly"] = "友善"
L["Hostile"] = "敵對"
L["Happy"] = "高興"
L["Neutral"] = "中立"
L["Unhappy"] = "不高興"
L["Custom"] = "自訂"
L["Taunts"] = "嘲諷"
L["Affection"] = "情感"
L["Greetings"] = "歡迎"
L["Combat"] = "戰鬥"
L["Self-Deprecating"] = "自嘲"
L["Reactions"] = "反應"
L["Other"] = "其它"
L["Actions"] = "動作"
L["Vocals"] = "聲音"

-- Genders
L["he"] = "他"
L["He"] = "他"
L["her"] = "她的"
L["Her"] = "她的"
L["his"] = "他的"
L["His"] = "他的"
L["she"] = "她"
L["She"] = "她"

-- Reactions
L["A"] = "動" -- "A"ction shortened
L["V"] = "音" -- "V"ocal shortened
L["AV"] = "動音" -- "A"ction/"V"ocal shortened

-- Actual addon texts

-- First (emote name only) is text produced
-- when there is no target.  Second (_target)
-- is what's produced when there is a target

-- The following tags:
-- <Target>, <He>, <he>, <She>, <she>
-- <His>, <his>, <Her>, <her>
-- MUST, MUST, MUST remain as is to work
-- They are localized above

-- Custom emotes
L["BIO"]="需要歇歇腿休息一下。"	   ;   	L["BIO_TARGET"]="你告訴<Target><he>需要歇歇腿休息一下。"
L["BLADEINTRO"]="will allen <his> Schwert vorstellen."	   ;   	L["BLADEINTRO_TARGET"]="will <Target> <his> Schwert vorstellen."
L["ESCAPE"]="緊張的咳嗽並尋找逃亡的手段。"	   ;   	L["ESCAPE_TARGET"]="<Target>緊張的咳嗽並尋找逃亡的手段。"

-- <- the translations under here are generated by the game ->

L["ABSENT"]="你看起來神情恍惚。"	   ;   	L["ABSENT_TARGET"]="你恍惚得看著<Target>。"
L["AGREE"]="你表示認同。"	   ;   	L["AGREE_TARGET"]="你贊同<Target>的觀點。"
L["AMAZE"]="你感到很驚奇!"	   ;   	L["AMAZE_TARGET"]="<Target>讓你感到很驚奇!"
L["ANGRY"]="你憤怒地揮起拳頭。"	   ;   	L["ANGRY_TARGET"]="你向<Target>憤怒地揮起拳頭。"
L["APOLOGIZE"]="你向大家表示道歉。對不起!"	   ;   	L["APOLOGIZE_TARGET"]="你向<Target>表示道歉。對不起!"
L["APPLAUD"]="你大聲喝采。好!"	   ;   	L["APPLAUD_TARGET"]="你向<Target>大聲喝采。真棒!"
L["ATTACKMYTARGET"]="你告訴所有人進攻某物。"	   ;   	L["ATTACKMYTARGET_TARGET"]="你要所有人進攻<Target>。"
L["AWE"]="你畏懼得四處張望。"	   ;   	L["AWE_TARGET"]="你畏懼得望著<Target>發愣。"
L["BACKPACK"]="你翻遍了你的背包。"	   ;   	L["BACKPACK_TARGET"]="你翻遍了你的背包。"
L["BADFEELING"]="你對這件事有著不好的預感..."	   ;   	L["BADFEELING_TARGET"]="你對<Target>有著不好的預感。"
L["BARK"]="你仰天長嘯。嗚...!"	   ;   	L["BARK_TARGET"]="你對著<Target>吠叫。"
L["BASHFUL"]="你非常害羞。"	   ;   	L["BASHFUL_TARGET"]="你太害羞了...因而無法引起<Target>的注意。"
L["BECKON"]="你招手示意大家都過去。"	   ;   	L["BECKON_TARGET"]="你招手示意<Target>過來。"
L["BEG"]="你向你周遭的人乞求。好可憐啊。"	   ;   	L["BEG_TARGET"]="你在乞求<Target>。好可憐啊。"
L["BITE"]="你四下張望，想找個人咬一口。"	   ;   	L["BITE_TARGET"]="你咬了<Target>一口。啊!"
L["BLAME"]="你為了發生的一切而自責不已。"	   ;   	L["BLAME_TARGET"]="你把一切都怪到<Target>頭上。"
L["BLANK"]="你茫然地盯著你的周圍看。"	   ;   	L["BLANK_TARGET"]="你茫然地盯著<Target>看。"
L["BLEED"]="你的傷口滲出了鮮血。"	   ;   	L["BLEED_TARGET"]="你的傷口滲出了鮮血。"
L["BLINK"]="你眨了眨眼。"	   ;   	L["BLINK_TARGET"]="你對<Target>眨了眨眼。"
L["BLUSH"]="你臉紅了。"	   ;   	L["BLUSH_TARGET"]="你對著<Target>臉紅了。"
L["BOGGLE"]="你對這個狀況感到吃驚。"	   ;   	L["BOGGLE_TARGET"]="你對<Target>感到吃驚。"
L["BONK"]="你重重的敲了一下自己的腦袋，真笨呀!"	   ;   	L["BONK_TARGET"]="你重重的敲了一下<Target>的腦袋，真笨呀!"
L["BORED"]="你已經對這種苦差事不厭其煩了!"	   ;   	L["BORED_TARGET"]="你對<Target>感到十分厭煩。"
L["BOUNCE"]="你正在上下跳躍。"	   ;   	L["BOUNCE_TARGET"]="你在<Target>面前上下跳躍。"
L["BOW"]="你優雅的鞠了躬。"	   ;   	L["BOW_TARGET"]="你向<Target>鞠躬。"
L["BRANDISH"]="你兇猛地揮舞著你的武器。"	   ;   	L["BRANDISH_TARGET"]="你對著<Target>兇猛地揮舞著你的武器。"
L["BRB"]="你告訴大家你馬上就回來。"	   ;   	L["BRB_TARGET"]="你告訴<Target>你會馬上回來。"
L["BREATH"]="你做一次深呼吸。"	   ;   	L["BREATH_TARGET"]="你要<Target>做一次深呼吸。"
L["BURP"]="你打了個響亮的嗝。"	   ;   	L["BURP_TARGET"]="你很沒有禮貌的對著<Target>打了個嗝。"
L["BYE"]="你向大家揮手告別。再見!"	   ;   	L["BYE_TARGET"]="你向<Target>揮手告別。再見!"
L["CACKLE"]="你見此情景咯咯的笑個不停。"	   ;   	L["CACKLE_TARGET"]="你對著<Target>咯咯的笑個不停。"
L["CALM"]="你保持冷靜。"	   ;   	L["CALM_TARGET"]="你試圖讓<Target>冷靜下來。"
L["CHALLENGE"]="你對所有人發出決鬥要求。放馬過來!"	   ;   	L["CHALLENGE_TARGET"]="你向<Target>發出決鬥要求。"
L["CHARGE"]="你開始衝鋒。"	   ;   	L["CHARGE_TARGET"]="你開始衝鋒。"
L["CHARM"]="你散發出魅力。"	   ;   	L["CHARM_TARGET"]="你認為<Target>很有魅力。"
L["CHEER"]="你大聲歡呼。"	   ;   	L["CHEER_TARGET"]="你為<Target>歡呼。"
L["CHICKEN"]="你像母雞一樣搧動著雙臂繞著圈子咯咯咯的叫!"	   ;   	L["CHICKEN_TARGET"]="你搧動著雙臂繞著<Target>咯咯咯地叫!"
L["CHUCKLE"]="你痴痴地笑著。"	   ;   	L["CHUCKLE_TARGET"]="你對著<Target>癡癡地笑。"
L["CHUG"]="你豪飲了你的飲料。"	   ;   	L["CHUG_TARGET"]="你向<Target>勸酒。乾杯!乾杯!乾杯!"
L["CLAP"]="你激動地鼓掌。"	   ;   	L["CLAP_TARGET"]="你激動地為<Target>鼓掌。"
L["COLD"]="你告訴大家你感到很冷。"	   ;   	L["COLD_TARGET"]="你告訴<Target>你感到很冷。"
L["COMFORT"]="你需要安慰。"	   ;   	L["COMFORT_TARGET"]="你安慰<Target>。"
L["COMMEND"]="你讚揚大家的工作完成得很出色。"	   ;   	L["COMMEND_TARGET"]="你讚揚<Target>的工作完成得很出色。"
L["CONFUSED"]="你覺得無助困惑。"	   ;   	L["CONFUSED_TARGET"]="你疑惑地看著<Target>。"
L["CONGRATULATE"]="你向你周遭的所有人表示祝賀。"	   ;   	L["CONGRATULATE_TARGET"]="你向<Target>表示祝賀。"
L["COUGH"]="你乾咳了幾下。"	   ;   	L["COUGH_TARGET"]="你對著<Target>咳嗽了幾下。"
L["COVEREARS"]="你摀住了耳朵。"	   ;   	L["COVEREARS_TARGET"]="你摀住了<Target>的耳朵。"
L["COWER"]="你害怕地退縮了。"	   ;   	L["COWER_TARGET"]="你一看到<Target>就害怕地退縮了。"
L["CRACK"]="你把手上的關節捏得咯咯作聲。"	   ;   	L["CRACK_TARGET"]="你把手上的關節捏得咯咯作聲，直直地望著<Target>。"
L["CRINGE"]="你因為恐懼而退縮了。"	   ;   	L["CRINGE_TARGET"]="你在<Target>的面前退縮了。"
L["CROSSARMS"]="你交叉著雙臂。"	   ;   	L["CROSSARMS_TARGET"]="你交叉著雙臂盯著<Target>看。哼!"
L["CRY"]="你哭了。"	   ;   	L["CRY_TARGET"]="你趴在<Target>的肩膀上泣不成聲。"
L["CUDDLE"]="你想要被擁抱一下。"	   ;   	L["CUDDLE_TARGET"]="你倚靠著<Target>睡去。"
L["CURIOUS"]="你對周圍的人流露出好奇心。"	   ;   	L["CURIOUS_TARGET"]="你對<Target>在做什麼感到很好奇。"
L["CURTSEY"]="你行了個屈膝禮。"	   ;   	L["CURTSEY_TARGET"]="你向<Target>行屈膝禮。"
L["DANCE"]="你開始跳舞。"	   ;   	L["DANCE_TARGET"]="你在和<Target>跳舞。"
L["DING"]="你升級啦，叮!"	   ;   	L["DING_TARGET"]="你恭喜<Target>升級了，叮!"
L["DISAGREE"]="你不同意。"	   ;   	L["DISAGREE_TARGET"]="你不同意<Target>。"
L["DOUBT"]="你懷疑情況是否會對你有利。"	   ;   	L["DOUBT_TARGET"]="你懷疑<Target>。"
L["DRINK"]="你舉起酒杯，然後一飲而盡。乾杯!"	   ;   	L["DRINK_TARGET"]="你向<Target>舉杯。乾杯!"
L["DROOL"]="一條長長的口水掛在你的嘴邊。"	   ;   	L["DROOL_TARGET"]="你看著<Target>流出了口水。"
L["DUCK"]="你蹲下掩護自己。"	   ;   	L["DUCK_TARGET"]="你躲在<Target>後面。"
L["EAT"]="你開始吃東西。"	   ;   	L["EAT_TARGET"]="你在<Target>面前開始吃東西。"
L["EMBARRASS"]="你尷尬的臉紅。"	   ;   	L["EMBARRASS_TARGET"]="<Target>讓你很不好意思。"
L["ENCOURAGE"]="你鼓勵周遭所有的人。你們行的!"	   ;   	L["ENCOURAGE_TARGET"]="你鼓勵<Target>。"
L["ENEMY"]="你警告所有人敵人就在附近。"	   ;   	L["ENEMY_TARGET"]="你警告<Target>敵人就在附近。"
L["EYE"]="你瞇起了眼睛。"	   ;   	L["EYE_TARGET"]="你上下打量了一下<Target>。"
L["EYEBROW"]="你好奇地挑了一下你的眉毛。"	   ;   	L["EYEBROW_TARGET"]="你對<Target>好奇地挑了一下你的眉毛。"
L["FAINT"]="你昏倒了。"	   ;   	L["FAINT_TARGET"]="你在<Target>的面前昏倒了。"
L["FART"]="你放了一個很響的屁。嗯...什麼東西這麼臭?"	   ;   	L["FART_TARGET"]="你靠近<Target>然後放了一個很響的屁。"
L["FIDGET"]="你顯得坐立不安。"	   ;   	L["FIDGET_TARGET"]="你等<Target>等得坐立不安。"
L["FLEE"]="你大喊所有人快跑!"	   ;   	L["FLEE_TARGET"]="你對<Target>大喊快跑!"
L["FLEX"]="你正在展示你的肌肉。哇，好壯啊!"	   ;   	L["FLEX_TARGET"]="你向<Target>展示你的肌肉。哇，好壯啊!"
L["FLIRT"]="你調情。"	   ;   	L["FLIRT_TARGET"]="你對<Target>調情。"
L["FLOP"]="你無助地走來走去。"	   ;   	L["FLOP_TARGET"]="你無助地在<Target>旁邊走來走去。"
L["FOLLOW"]="你示意所有人跟著。"	   ;   	L["FOLLOW_TARGET"]="你示意<Target>跟著。"
L["FROWN"]="你皺著眉頭。"	   ;   	L["FROWN_TARGET"]="你失望地對<Target>皺起了眉頭。"
L["GASP"]="你顯得氣喘吁吁。"	   ;   	L["GASP_TARGET"]="你對著<Target>倒抽了一口氣。"
L["GAZE"]="你凝視著遠方。"	   ;   	L["GAZE_TARGET"]="你渴求得凝視著<Target>。"
L["GIGGLE"]="你在咯咯地傻笑。"	   ;   	L["GIGGLE_TARGET"]="你對著<Target>咯咯地傻笑。"
L["GLARE"]="你生氣地瞪大了眼睛。"	   ;   	L["GLARE_TARGET"]="你生氣地對著<Target>瞪大了眼睛。"
L["GLOAT"]="你幸災樂禍於大家的不幸。"	   ;   	L["GLOAT_TARGET"]="你幸災樂禍於<Target>的不幸。"
L["GLOWER"]="你怒視著周遭所有的人。"	   ;   	L["GLOWER_TARGET"]="你怒視著<Target>。"
L["GO"]="你告訴大家該走了。"	   ;   	L["GO_TARGET"]="你告訴<Target>該走了。"
L["GOING"]="你得走了。"	   ;   	L["GOING_TARGET"]="你告訴<Target>你得走了。"
L["GOLFCLAP"]="你心不在焉地鼓掌，很明顯不太在意。"	   ;   	L["GOLFCLAP_TARGET"]="你為<Target>鼓掌，但很明顯不太在意。。"
L["GREET"]="你熱情地問候大家。"	   ;   	L["GREET_TARGET"]="你熱情問候<Target>。"
L["GRIN"]="你邪惡地笑了笑。"	   ;   	L["GRIN_TARGET"]="你邪惡地對<Target>笑了笑。"
L["GROAN"]="你開始呻吟。"	   ;   	L["GROAN_TARGET"]="你對著<Target>呻吟。"
L["GROVEL"]="你卑微地跪在地上, 沉溺於奉承。"	   ;   	L["GROVEL_TARGET"]="你在<Target>面前卑躬屈膝，好像一個屈從的苦工一樣。"
L["GROWL"]="你在高聲怒吼。"	   ;   	L["GROWL_TARGET"]="你對著<Target>高聲怒吼。"
L["GUFFAW"]="你放聲大笑。"	   ;   	L["GUFFAW_TARGET"]="你看了<Target>一眼然後哈哈大笑。"
L["HAIL"]="你和周圍所有的人打招呼。"	   ;   	L["HAIL_TARGET"]="你和<Target>打招呼。"
L["HAPPY"]="你顯得非常高興!"	   ;   	L["HAPPY_TARGET"]="你感到和<Target>在一起很開心!"
L["HEADACHE"]="你頭疼不已。"	   ;   	L["HEADACHE_TARGET"]="你因為<Target>的白痴舉動頭疼不已。"
L["HEALME"]="你大聲請求治療!"	   ;   	L["HEALME_TARGET"]="你大聲請求治療!"
L["HELLO"]="你真心地向大家表示問候。"	   ;   	L["HELLO_TARGET"]="你真心地向<Target>表示問候。"
L["HELPME"]="你大聲呼救!"	   ;   	L["HELPME_TARGET"]="你大聲呼救!"
L["HICCUP"]="你大聲的打嗝。"	   ;   	L["HICCUP_TARGET"]="你大聲的打嗝。"
L["HISS"]="你對周遭所有人發出噓聲。"	   ;   	L["HISS_TARGET"]="你對<Target>發出噓聲。"
L["HOLDHAND"]="你希望有人能牽著你的手。"	   ;   	L["HOLDHAND_TARGET"]="你牽起了<Target>的手。"
L["HUG"]="你需要一個擁抱!"	   ;   	L["HUG_TARGET"]="你擁抱了<Target>。"
L["HUNGRY"]="你感到很餓!"	   ;   	L["HUNGRY_TARGET"]="你感到很餓。也許在<Target>那裡可以找到一些食物。"
L["HURRY"]="你試著趕上速度。"	   ;   	L["HURRY_TARGET"]="你催促<Target>動作快一點。"
L["IDEA"]="你有個好主意!"	   ;   	L["IDEA_TARGET"]="你有個好主意!"
L["INCOMING"]="你警告大家敵人來襲!"	   ;   	L["INCOMING_TARGET"]="你指著<Target>就是來襲的敵人!"
L["INSULT"]="你認為周遭所有的人都是沒有教養的傢伙。"	   ;   	L["INSULT_TARGET"]="你認為<Target>是個沒教養的傢伙。"
L["INTRODUCE"]="你向大家介紹你自己。"	   ;   	L["INTRODUCE_TARGET"]="你向<Target>作了一番自我介紹。"
L["JEALOUS"]="你嫉妒周遭所有的人。"	   ;   	L["JEALOUS_TARGET"]="你嫉妒<Target>。"
L["JK"]="你只是在開玩笑。"	   ;   	L["JK_TARGET"]="你告訴<Target>你只是在開玩笑。"
L["JOKE"]="你講了一個笑話。"	   ;   	L["JOKE_TARGET"]="你給<Target>講了一個笑話。"
L["KISS"]="你拋出一個飛吻。"	   ;   	L["KISS_TARGET"]="你給了<Target>一個飛吻。"
L["KNEEL"]="你跪了下來。"	   ;   	L["KNEEL_TARGET"]="你在<Target>面前跪下。"
L["LAUGH"]="你大笑。"	   ;   	L["LAUGH_TARGET"]="你在嘲笑<Target>。"
L["LAYDOWN"]="你躺了下來。"	   ;   	L["LAYDOWN_TARGET"]="你在<Target>面前躺下。"
L["LICK"]="你舔了舔嘴唇。"	   ;   	L["LICK_TARGET"]="你舔了舔<Target>。"
L["LISTEN"]="你正在仔細地聆聽!"	   ;   	L["LISTEN_TARGET"]="你認真地聽<Target>說話。"
L["LOOK"]="你看著四周。"	   ;   	L["LOOK_TARGET"]="你看著<Target>。"
L["LOST"]="你徹底地失敗了。"	   ;   	L["LOST_TARGET"]="你告訴<Target>你已經徹底失敗了。"
L["LOVE"]="你感受到了深深的愛意。"	   ;   	L["LOVE_TARGET"]="你愛<Target>。"
L["LUCK"]="你祝所有人好運。"	   ;   	L["LUCK_TARGET"]="你祝<Target>好運。"
L["MAP"]="你攤開了地圖。"	   ;   	L["MAP_TARGET"]="你攤開了地圖。"
L["MASSAGE"]="你需要按摩一下!"	   ;   	L["MASSAGE_TARGET"]="你幫<Target>按摩肩膀。"
L["MERCY"]="你求饒。"	   ;   	L["MERCY_TARGET"]="你求<Target>饒命。"
L["MOAN"]="你輕輕地呻吟。"	   ;   	L["MOAN_TARGET"]="你對著<Target>輕輕地呻吟。"
L["MOCK"]="你看破紅塵，覺得一切都無所謂了。"	   ;   	L["MOCK_TARGET"]="你嘲笑<Target>的愚蠢。"
L["MOO"]="哞～～～～～～"	   ;   	L["MOO_TARGET"]="你對<Target>發出牛叫聲。哞～～～～～～"
L["MOON"]="你把屁股對著大家。"	   ;   	L["MOON_TARGET"]="你把屁股對著<Target>。"
L["MOURN"]="你深深的陷入對於死者的哀思中。"	   ;   	L["MOURN_TARGET"]="你深深的陷入對於<Target>之死的哀思中。"
L["MUTTER"]="你生氣得對自己抱怨。哼!"	   ;   	L["MUTTER_TARGET"]="你生氣得對<Target>抱怨。哼!"
L["NERVOUS"]="你緊張得四處張望。"	   ;   	L["NERVOUS_TARGET"]="你緊張得看著<Target>。"
L["NO"]="你斬釘截鐵地說了個不字。"	   ;   	L["NO_TARGET"]="你堅決地對<Target>說不。不能發生。"
L["NOD"]="你點了點頭。"	   ;   	L["NOD_TARGET"]="你對<Target>點了點頭。"
L["NOSEPICK"]="你無聊地挖鼻孔來打發時間。"	   ;   	L["NOSEPICK_TARGET"]="你挖了挖鼻孔，把手指伸到<Target>面前。"
L["OBJECT"]="你反對!"	   ;   	L["OBJECT_TARGET"]="你反對<Target>的意見。"
L["OFFER"]="你想要做出提議。"	   ;   	L["OFFER_TARGET"]="你試著對<Target>提出一件難以拒絕的提議。"
L["OOM"]="你宣佈你的法力不足!"	   ;   	L["OOM_TARGET"]="你宣佈你的法力不足!"
L["OPENFIRE"]="你命令開火。"	   ;   	L["OPENFIRE_TARGET"]="你命令開火。"
L["PANIC"]="你驚恐地跑來跑去。"	   ;   	L["PANIC_TARGET"]="你看了一眼<Target>，然後大驚失色。"
L["PAT"]="你需要一些安慰。"	   ;   	L["PAT_TARGET"]="你輕輕拍了拍<Target>。"
L["PEER"]="你仔細地打量了一下四周。"	   ;   	L["PEER_TARGET"]="你仔細地打量了一下<Target>。"
L["PET"]="你需要被撫摸。"	   ;   	L["PET_TARGET"]="你撫摸<Target>。"
L["PINCH"]="你捏了你自己一把。"	   ;   	L["PINCH_TARGET"]="你捏了<Target>一把。"
L["PITY"]="你對你周圍的人表示同情。"	   ;   	L["PITY_TARGET"]="你輕蔑地看著<Target>這個可憐的傢伙。"
L["PLEAD"]="你跪了下來，絕望地懇求著。"	   ;   	L["PLEAD_TARGET"]="你向<Target>懇求。"
L["POINT"]="你指向遠方。"	   ;   	L["POINT_TARGET"]="你指著<Target>。"
L["POKE"]="你戳了戳你的肚子然後咯咯地傻笑。"	   ;   	L["POKE_TARGET"]="你戳了戳<Target>說:「嗨!」"
L["PONDER"]="你仔細斟酌著當前的狀況。"	   ;   	L["PONDER_TARGET"]="你對<Target>的行為認真的思考著。"
L["POUNCE"]="你從暗處撲了出來。"	   ;   	L["POUNCE_TARGET"]="你向著<Target>撲了過去。"
L["POUT"]="你對周遭所有的人噘嘴巴。"	   ;   	L["POUT_TARGET"]="你對著<Target>噘嘴巴。"
L["PRAISE"]="你讚美光明的力量。"	   ;   	L["PRAISE_TARGET"]="你對於<Target>大加讚賞。"
L["PRAY"]="你虔誠地向神祈禱。"	   ;   	L["PRAY_TARGET"]="你虔誠地為<Target>祈禱。"
L["PROMISE"]=""	   ;   	L["PROMISE_TARGET"]="你對<Target>作出承諾。"
L["PROUD"]="你對自己感到驕傲。"	   ;   	L["PROUD_TARGET"]="你對<Target>感到驕傲。"
L["PULSE"]="你替自己量了脈搏。"	   ;   	L["PULSE_TARGET"]="你替<Target>量了脈搏。噢不!"
L["PUNCH"]="你搥了自己一拳。"	   ;   	L["PUNCH_TARGET"]="你搥了<Target>的肩膀一拳。"
L["PURR"]="你像貓咪一樣發出呼嚕呼嚕的聲音。"	   ;   	L["PURR_TARGET"]="你對著<Target>發出呼嚕呼嚕的聲音。"
L["PUZZLE"]="你被搞糊塗了。這到底是怎麼一回事啊?"	   ;   	L["PUZZLE_TARGET"]="你被<Target>搞糊塗了。"
L["RAISE"]="你舉起了你的手。"	   ;   	L["RAISE_TARGET"]="你看著<Target>，舉起了你的手。"
L["RASP"]="你做了個粗魯的手勢。"	   ;   	L["RASP_TARGET"]="你對<Target>做了個粗魯的手勢。"
L["READY"]="你告訴大家你已經準備好了!"	   ;   	L["READY_TARGET"]="你告訴<Target>你已經準備好了。"
L["REGRET"]="你滿是悔意。"	   ;   	L["REGRET_TARGET"]="你認為<Target>會後悔的。"
L["REVENGE"]="你誓言要完成復仇。"	   ;   	L["REVENGE_TARGET"]="你誓言要向<Target>復仇。"
L["ROAR"]="你發出野獸般的狂吼。好兇啊!"	   ;   	L["ROAR_TARGET"]="你對著<Target>發出野獸般的狂吼。好可怕啊!"
L["ROFL"]="你笑翻在地。"	   ;   	L["ROFL_TARGET"]="你對著<Target>笑翻在地。"
L["ROLLEYES"]="你的眼珠骨碌碌得轉。"	   ;   	L["ROLLEYES_TARGET"]="你的眼珠對著<Target>骨碌碌得轉。"
L["RUDE"]="你做了個粗魯的手勢。"	   ;   	L["RUDE_TARGET"]="你對<Target>做了個粗魯的手勢。"
L["RUFFLE"]="你撥亂了自己的頭髮。"	   ;   	L["RUFFLE_TARGET"]="你撥亂了<Target>的頭髮。"
L["SAD"]="你看起來垂頭喪氣。"	   ;   	L["SAD_TARGET"]="你看起來垂頭喪氣。"   --new
L["SALUTE"]="你立正敬禮。"	   ;   	L["SALUTE_TARGET"]="你滿懷敬意地向<Target>致敬。"  --new
L["SCARED"]="你看起來十分驚恐不安。"	   ;   	L["SCARED_TARGET"]="你非常害怕<Target>。"  --new
L["SCOFF"]="你嘲弄。"	   ;   	L["SCOFF_TARGET"]="你嘲弄<Target>。"		--new
L["SCOLD"]="你責備自己。"	   ;   	L["SCOLD_TARGET"]="你責備<Target>。"		--new
L["SCOWL"]="你表現出不悅。"	   ;   	L["SCOWL_TARGET"]="你對<Target>大感不悅。"		--new
L["SCRATCH"]="你抓了抓你自己。啊，舒服多了!"	   ;   	L["SCRATCH_TARGET"]="你抓了抓<Target>。真陰險!"		--new
L["SEARCH"]="你正搜尋著什麼。"	   ;   	L["SEARCH_TARGET"]="你在<Target>身上搜尋著什麼。"		--new
L["SEXY"]="你的裝扮實在是太有誘惑力了...讓人怦然心動。"	   ;   	L["SEXY_TARGET"]="你覺得<Target>魅力十足。"		--new
L["SHAKE"]="你扭了扭屁股。"	   ;   	L["SHAKE_TARGET"]="你對著<Target>扭了扭屁股。"		--new			
L["SHAKEFIST"]="你揮舞著拳頭。"	   ;   	L["SHAKEFIST_TARGET"]="你對著<Target>揮舞著拳頭。"		--new
L["SHIFTY"]="你的眼神可疑得四處張望。"	   ;   	L["SHIFTY_TARGET"]="你奸詐得看著<Target>。"		--new
L["SHIMMY"]="你在眾人面前舞動。"	   ;   	L["SHIMMY_TARGET"]="你在<Target>面前舞動。"		--new
L["SHIVER"]="你冷得不斷顫抖。"	   ;   	L["SHIVER_TARGET"]="你倚靠著<Target>冷得不斷顫抖。"		--new
L["SHOO"]="你發出噓聲讓那些討厭的傢伙走開。"	   ;   	L["SHOO_TARGET"]="你噓走了<Target>。走開，討厭的傢伙!"		--new
L["SHOUT"]="你在大叫。"	   ;   	L["SHOUT_TARGET"]="你對著<Target>大叫。"		--new
L["SHRUG"]="你聳了聳肩說:「天知道。」"	   ;   	L["SHRUG_TARGET"]="你對著<Target>聳了聳肩說:「天知道。」"		--new
L["SHUDDER"]="你渾身發抖。"	   ;   	L["SHUDDER_TARGET"]="你因為見到了<Target>而渾身發抖。"		--new
L["SHY"]="你顯得十分害羞!"	   ;   	L["SHY_TARGET"]="你在<Target>面前感到很害羞。"		--new
L["SIGH"]="你長長地嘆了一口氣。"	   ;   	L["SIGH_TARGET"]="你對著<Target>嘆了口氣。"		--new
L["SIGNAL"]="你在打暗號。"	   ;   	L["SIGNAL_TARGET"]="你對<Target>打暗號。"		--new
L["SILENCE"]="你要大家安靜。噓～～～～!"	   ;   	L["SILENCE_TARGET"]="你要<Target>安靜。噓～～～～!"		--new
L["SING"]="你突然唱起了歌來。"	   ;   	L["SING_TARGET"]="你對著<Target>唱情歌。"		--new
L["SIT"]="<動作>"	   ;   	L["SIT_TARGET"]="<動作>"		--new
L["SLAP"]="你賞了自己一個耳光，啊!"	   ;   	L["SLAP_TARGET"]="你賞了<Target>一個耳光，啊!"		--new
L["SLEEP"]="你進入了夢鄉。Zzzzzzz..."	   ;   	L["SLEEP_TARGET"]="你進入了夢鄉。Zzzzzzz..."		--new
L["SMACK"]="你拍打自己的額頭。"	   ;   	L["SMACK_TARGET"]="你朝<Target>的頭不停拍打。"		--new
L["SMILE"]="你露出了微笑。"	   ;   	L["SMILE_TARGET"]="你對<Target>露出了微笑。"		--new
L["SMIRK"]="你的臉上漸漸的露出了奸笑。"	   ;   	L["SMIRK_TARGET"]="你對著<Target>奸笑。"		--new
L["SNAP"]="你彈著手指。"	   ;   	L["SNAP_TARGET"]="你對<Target>彈著手指。"		--new
L["SNARL"]="你呲牙咧嘴地開始怒吼。"	   ;   	L["SNARL_TARGET"]="你呲牙咧嘴地朝著<Target>怒吼。"		--new
L["SNEAK"]="你試著潛行逃走。"	   ;   	L["SNEAK_TARGET"]="你試著要從<Target>面前潛行逃走。"		--new
L["SNEEZE"]="你打了一個噴嚏。哈啾!"	   ;   	L["SNEEZE_TARGET"]="你對著<Target>打噴嚏。哈啾!"		--new
L["SNICKER"]="你暗自偷笑。"	   ;   	L["SNICKER_TARGET"]="你對著<Target>竊笑。"		--new
L["SNIFF"]="你嗅了嗅周圍的空氣。"	   ;   	L["SNIFF_TARGET"]="你仔細的嗅了嗅<Target>。"		--new
L["SNORT"]="你哼氣出聲。"	   ;   	L["SNORT_TARGET"]="你嘲弄得對<Target>哼氣出聲。"		--new
L["SNUB"]="你大聲訓斥著周圍卑賤的苦工。"	   ;   	L["SNUB_TARGET"]="你對<Target>十分冷淡。"		--new
L["SOOTHE"]="你需要安慰。"	   ;   	L["SOOTHE_TARGET"]="你安撫著<Target>。一切...一切都會好的。"		--new
L["SPIT"]="你朝地上吐口水。"	   ;   	L["SPIT_TARGET"]="你對<Target>吐口水。"		--new
L["SQUEAL"]="你像豬一樣的嚎叫。"	   ;   	L["SQUEAL_TARGET"]="你對<Target>發出豬叫聲。"		--new
L["STAND"]="<動作>"	   ;   	L["STAND_TARGET"]="<動作>"		--new
L["STARE"]="你凝視著遠方。"	   ;   	L["STARE_TARGET"]="你用目光壓倒了<Target>。"	--new
L["STINK"]="你聞了聞周圍的空氣。哇，有些人好臭啊!"	   ;   	L["STINK_TARGET"]="你把鼻子湊過來聞了聞<Target>。哇，你好臭啊!"		--new
L["SURPRISED"]="你感到非常的驚訝!"	   ;   	L["SURPRISED_TARGET"]="你對<Target>的行為感到很驚訝。"		--new
L["SURRENDER"]="你向對手投降。"	   ;   	L["SURRENDER_TARGET"]="你向<Target>投降。失敗的滋味真不好受啊..."		--new
L["SUSPICIOUS"]="你懷疑的瞇起了雙眼。"	   ;   	L["SUSPICIOUS_TARGET"]="你對<Target>感到十分可疑。"		--new
L["SWEAT"]="你渾身冒汗。"	   ;   	L["SWEAT_TARGET"]="你一見到<Target>就渾身冒汗。"		--new
L["TALK"]="看起來沒有人感興趣，你只能自言自語。"	   ;   	L["TALK_TARGET"]="你有些事想和<Target>討論一下。"  --new
L["TALKEX"]="你正和大家興高采烈地交談著。"	   ;   	L["TALKEX_TARGET"]="你正和<Target>興高采烈地交談著。"  --new
L["TALKQ"]="你想要知道生活的意義。"	   ;   	L["TALKQ_TARGET"]="你向<Target>提問。"		--new
L["TAP"]="你不耐煩地用腳打著拍子，快一點!"	   ;   	L["TAP_TARGET"]="你一邊用腳打著拍子一邊等待<Target>。"		--new
L["TAUNT"]="你對周遭所有的人做了個嘲弄的姿勢。來啊!笨蛋!"	   ;   	L["TAUNT_TARGET"]="你對<Target>做了個嘲弄的姿勢。來啊!"		--new
L["TEASE"]="你真是個喜歡嘲弄別人的傢伙。"	   ;   	L["TEASE_TARGET"]="你嘲弄了<Target>一番。"		--new
L["THANK"]="你向周遭所有的人表示感謝。"	   ;   	L["THANK_TARGET"]="你對<Target>表示感謝。"  	--new
L["THINK"]="你陷入了沉思。"	   ;   	L["THINK_TARGET"]="你想到<Target>。"		--new
L["THIRSTY"]="你感到非常的口渴。有沒有人能給點喝的?"	   ;   	L["THIRSTY_TARGET"]="你告訴<Target>你很渴。朋友，有沒有可以喝的?"		--new
L["THREATEN"]="你以死亡的懲罰威脅大家。"	   ;   	L["THREATEN_TARGET"]="你以死亡的懲罰威脅<Target>。"		--new
L["TICKLE"]="你想要被搔癢。嘿嘿!"	   ;   	L["TICKLE_TARGET"]="你對<Target>搔癢。嘿嘿!"		--new
L["TIRED"]="你告訴大家你已經很累了。"	   ;   	L["TIRED_TARGET"]="你告訴<Target>你已經很累了。"		--new
L["TRAIN"]="<Choo Choo火車動作和聲音>"	   ;   	L["TRAIN_TARGET"]="<Choo Choo火車動作和聲音>"		--new
L["TRUCE"]="你提議休戰。"	   ;   	L["TRUCE_TARGET"]="你對<Target>提議休戰。"		--new
L["TWIDDLE"]="你撥弄著你的拇指。"	   ;   	L["TWIDDLE_TARGET"]="你撥弄著你的拇指。"		--new
L["VETO"]="你極力反對這樣的行為。"	   ;   	L["VETO_TARGET"]="你反對<Target>這樣做。"		--new
L["VICTORY"]="你沉醉在勝利的榮耀之中。"	   ;   	L["VICTORY_TARGET"]="你與<Target>一起分享勝利的榮耀。"		--new
L["VIOLIN"]="你小聲地哭了起來。"	   ;   	L["VIOLIN_TARGET"]="你在<Target>面前小聲地哭了起來。"		--new
L["WAIT"]="你要所有人等著。"	   ;   	L["WAIT_TARGET"]="你要<Target>等著。"		--new
L["WARN"]="你警告大家。"	   ;   	L["WARN_TARGET"]="你警告<Target>."		--new
L["WAVE"]="你揮了揮手。"	   ;   	L["WAVE_TARGET"]="你向<Target>揮手致意。"		--new
L["WELCOME"]="你向大家表示歡迎。"	   ;   	L["WELCOME_TARGET"]="你歡迎<Target>的到來。"		--new
L["WHINE"]="你在可憐兮兮地訴苦。"	   ;   	L["WHINE_TARGET"]="你可憐兮兮地向<Target>訴苦。"		--new
L["WHISTLE"]="你響亮地吹了一聲口哨。"	   ;   	L["WHISTLE_TARGET"]="你對著<Target>吹了一聲口哨。"		--new
L["WINK"]="你神秘地眨了眨眼。"	   ;   	L["WINK_TARGET"]="你神秘地朝<Target>眨了眨眼。"		--new
L["WORK"]="你開始工作。"	   ;   	L["WORK_TARGET"]="你和<Target>一起工作。"		--new
L["YAWN"]="你深深地打了個哈欠。"	   ;   	L["YAWN_TARGET"]="你對著<Target>深深地打了個哈欠。"		--new
L["YW"]="你很高興能幫忙。"	   ;   	L["YW_TARGET"]="你很高興能幫忙<Target>。"		--new
